name: Build Settings Reset

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for building settings reset firmware'
        required: false
        default: 'Manual settings reset needed'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build settings_reset firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (settings_reset)
        run: west build -s zmk/app -b seeeduino_xiao_ble -- -DZMK_CONFIG=${GITHUB_WORKSPACE}/config -DSHIELD=settings_reset

      - name: Create firmware artifact
        run: |
          mkdir -p firmware
          if [ -f build/zephyr/zmk.uf2 ]; then
            cp build/zephyr/zmk.uf2 firmware/settings_reset.uf2
          else
            echo "Error: zmk.uf2 not found"
            exit 1
          fi

      - name: Upload settings reset firmware
        uses: actions/upload-artifact@v4
        with:
          name: settings_reset
          path: firmware/settings_reset.uf2
          retention-days: 30

      - name: Build summary
        run: |
          echo "## Settings Reset Firmware Built Successfully 🔧" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Reason:** ${{ github.event.inputs.reason }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Usage Instructions:**" >> $GITHUB_STEP_SUMMARY
          echo "1. Download the \`settings_reset.uf2\` artifact" >> $GITHUB_STEP_SUMMARY
          echo "2. Put your keyboard into bootloader mode" >> $GITHUB_STEP_SUMMARY
          echo "3. Flash the settings reset firmware" >> $GITHUB_STEP_SUMMARY
          echo "4. Power cycle the keyboard" >> $GITHUB_STEP_SUMMARY
          echo "5. Flash your normal firmware back" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "⚠️  **Warning:** This will erase all saved settings, bonds, and macros!"